version: '3.9'

networks:
  basisregisters:

services:
  basisregisters.kafka-topic-transfer:
    image: ghcr.io/informatievlaanderen/kafka-topic-transfer:0.0.3
    container_name: basisregisters.kafka-topic-transfer
    volumes:
      - "/home/yusuf/repos/fork/kafka-transfer/src/kafka.transfer.app/appsettings.linux.json:/app/appsettings.json"
    restart: always
    networks:
      - basisregisters
    tty: true
    stdin_open: true
